### ISSUE TITLE
Enhancement: make network errors more visible

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#10]
Hello,

I think we could make network errors more visible, perhaps by adding a little bit of color.

Here is what it could look like (with Material Red 100) :
![error-material-red-100](https://cloud.githubusercontent.com/assets/15214466/13407769/6860a7f8-df2a-11e5-9f3d-5b109a0838bb.png)

**Comment by niqdev** [comment]
Hi,
the idea is right, actually only for Light and Automation, not Device, right?

What about to distinguish Network error from Response error?
I don't like that if we open the app without network connection we see all cards red. Network error should display a [Snackbar](http://developer.android.com/reference/android/support/design/widget/Snackbar.html) and only the warning (no red background)

Moreover, I think that if we don't plan to use any other background colour for other cards could fine, otherwise it will become a [harlequin style](https://en.wikipedia.org/wiki/Harlequin)

**Comment by moreau-nicolas** [comment]
Actually I implemented this change for Devices too, but it's in a dedicated commit so it can be reverted easily. I thought it would be useful to distinguish between network error and bad request too, but I agree that perhaps it's not the best way to do it, Harlequin and all. ;-) 

I like the SnackBar idea, but I have something else in mind: don't list devices for which there is a network error, show an error count instead. And maybe a shortcut to the wifi settings. What do you think ?

**Comment by moreau-nicolas** [comment]
Other idea: Perhaps only the warning icon could be colorized, not the entire card background ?

**Comment by moreau-nicolas** [comment]
Ok. Perhaps the solution is two-fold :

1. All devices remain visible on network error but we change the alert icon to use color, for example holo_red_light
2. We add a SnackBar-like view above the device list that is shown when a network error occurs. The view informs the user about the connectivity problem and might provide a link to the wifi settings or a "refresh" action . The view disappears if the connection is restored.


Do you agree with this?

**Comment by niqdev** [comment]
Perfect, the only things is that I would like to keep consistency for the SnackBar in one place.
I would just transform `MainActivity#showSnackbar` in an event using greenrobot.
What do you think?

**Comment by niqdev** [comment]
I've noticed that AndroidStudio gives a warning that colour reference does't work correctly on version < 21, so I changed.
Moreover I've used RED_DARK from this [palette](https://www.materialpalette.com/red/orange), tell me if you like it!

**Comment by moreau-nicolas** [comment]
Yes, it is nice, thank you ! I didn't see the warning. :(

**Comment by niqdev** [comment]
I've updated also the colour for device status with same red

**Comment by moreau-nicolas** [comment]
Cool !

**Comment by moreau-nicolas** [comment]
The next step is adding the persistent view explaining the error, would you like to do it or should I ?

**Comment by moreau-nicolas** [comment]
I will add the persistent view soon, @niqdev could you please assign me to the issue?

**Comment by niqdev** [comment]
I've added you as member, otherwise I can't assign you the issue

**Comment by moreau-nicolas** [comment]
Thanks !

**Comment by niqdev** [comment]
I can't yet, you need to accept the invitation! Please verify your email!

**Comment by moreau-nicolas** [comment]
I think that the "network error" snackbar should only be displayed when we can't reach the Gateway, not when a device's status cannot be retrieved. Do you agree ?

I'm not sure which duration the Snackbar should have:
- LENGTH_LONG ?
- LENGTH_INDEFINITE ?

What do you think ?

**Comment by niqdev** [comment]
Yes, I agree. We already have the red triangle on cards for device status error.
I think LENGTH_LONG is easier, if we use LENGTH_INDEFINITE the Snackbar should also disappear as soon as network become available.
What do you think?

**Comment by moreau-nicolas** [comment]
I think it will boil down to this question : do we want to provide an Action on the SnackBar (to the Wifi settings for example) or not ?

If we don't then I'll be fine with ```LENGTH_LONG```, otherwise I'd rather stick to ```LENGTH_INDEFINITE``` because with ```LENGTH_LONG``` the SnackBar disappears too quickly. :disappointed: 

I don't think that we should dismiss the SnackBar as soon as the network becomes available. It seems enough to dismiss it when the user does a *swipe-to-refresh*.

**Comment by moreau-nicolas** [comment]
I can't seem to find a way to reliably distinguish between network errors and device errors. Do you have any idea about how to do this ?

**Comment by niqdev** [comment]
All right, currently this check is not centralized in a single point, but each card and its related service invocation has this info in `doOnError(throwable)` or when we set the status.
Probably, for our needs, is enough to check in `DeviceListFragment` if we have a reliable network/wifi connection, something like `ConnectivityManager/NetworkInfo`.
Moreover I would add the implementation or in `CommonService` or probably in a new service for wrap system utility or maybe in a dedicated one like `NetworkService`.
```java
@Subscribe
public void onEvent(UpdateDeviceListEvent event) {
  // VERIFY NETWORK STATUS HERE
  swipeRefreshLayoutDeviceList.setRefreshing(true);
  initCards(event.getEnvironmentId());
}
```
What do you think?

**Comment by niqdev** [comment]
@moreau-nicolas, just to know if you already worked on it, did you check this?

**Comment by moreau-nicolas** [comment]
@niqdev yes, I'm still on this, I like what you're proposing, I've been short on spare time lately, sorry.
I'll try and push something this week.

**Comment by niqdev** [comment]
Don't worry! No rush at all! The whole project is just for fun :stuck_out_tongue_winking_eye:

**Comment by niqdev** [comment]
Even if I've added this methods that could help with the issue
* `CommonService#hasNetworkAccess`
* `CommonService#hasInternetAccess`

I think that the red triangle is already enough for the moment.

If for example I'm at home in a private network without internet connection the app should work correctly because I've direct access to the gateway, while if I'm outside even if there is an internet connection the gateway maybe is not accessible without a VPN.

Moreover with new Ip Camera features user is not restricted to use any gateway.

For this reason I will close the issue.

**Comment by moreau-nicolas** [comment]
Sorry for not being active in the last few weeks / months, I've changed jobs in March and have not had a lot of spare time since then.

:+1: for closing the issue.

**Comment by niqdev** [comment]
Hi! No problem, I hope you are doing well!

**Comment by moreau-nicolas** [comment]
Yep. It was a change by choice, and it is a good change. :)
Hope you're weel too.
