### ISSUE TITLE
Profile creation not working

### ISSUE THREAD

**Issue by olaquetal** [openwebnet/openwebnet-android#107]
Hello
I have OpenWebNet 3.4.1. Thanks a lot for this great application. 
I'm using a samsung S6.
I enabled my google account in the application. 
Everything seems to work fine except that I can't create a profile to share my configuration.
When I select "Profiles" I get the screen attached, with the error "nothing found" and "no connexion"

![Screenshot_20211205-185920](https://user-images.githubusercontent.com/3658648/145695733-9a92bee1-768c-47d5-9952-74f693358aed.jpg)

 Thank you!

**Comment by olaquetal** [comment]
Hello,
I tried to add a profile when I was very close to my wifi router, and it worked! 
I had the "+" button and I could create a profile that I shared with my son adding he's email. 
But when I am not very close to the wifi routers, the profile screen remains empty, don't know if the "share" feature can work this way.
My son installed the application but nothing special appeared yet and we didn't had an email.
Thanks a lot for help

**Comment by niqdev** [comment]
Hi,
thanks for the details, and sorry for the late reply.

So, it looks like the issue with the creation was an internet connection problem on your side. When accessing the profile features, make sure your phone have access to both your home network and internet, or it won't work.

Regarding the sharing functionality, *please don't share your personal details on github*, but can you confirm that
* your son logged in first on his phone before attempting to share the account
* both emails are valid **gmail.com** accounts
* you've entered only the prefix e.g. if your email is **name.surname**@gmail.com, you've entered only **name.surname**

If you didn't logged in before it shouldn't be a big deal, just do it now and then try to re-share the profile.

If the problem persist, there might be an issue and I'll investigate it. If all the above didn't work, please send me at `info AT openwebnet.xyz` both the emails you've used. Please, do NOT share them on github for your own privacy.

Thanks, and sorry for the inconvenience, I'll look after it. Just be patience if i'm slow responding!

**Comment by olaquetal** [comment]
Hello,
I found the problem, which was related to my phone. The battery usage parameter was set to medium, which didn't allow the processor to run at max speed. I changed it to "normal" and I could add a profile. I then had a problem because the app was crashing every time I tried to add a device (light or shutter). I uninstalled and reinstalled it and it's fine now. 
Another question: at the beginning I shared my profile before creating the devices and I thought it was not working.  I understand that a "profile" is like a backup so I need to finish to input all my devices before sharing it, correct ?
You can also close the issue please

**Comment by niqdev** [comment]
Hi,
I've missed your response, sorry. Thanks for the feedback. Yes, the profile is like a "backup" but it's more generic, you can have completely different profiles on the same phone, and share them with different users.

> I need to finish to input all my devices before sharing it
It depends on what you want to share

I hope it helped!
