### ISSUE TITLE
Enhancement: create a richer Light card

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#14]
Hello,

I think the Light card would be more interesting if it offered more interaction than just "Toggle".

Something like : 
![richer-light-card](https://cloud.githubusercontent.com/assets/15214466/13409520/a9917db6-df33-11e5-8458-5462f982824b.png)

It would actually be useful in a scenario where a user would like to have a "General" switch : it does not make sense to turn all lights on before turning them off just because there is only a toggle switch...

**Comment by niqdev** [comment]
Hi,
actually I think this is a bug, we should also handle groups `*1*1 - #2 - ##`. Now only numbers are allowed.
We should also give the possibility, like for Device, to choose if fire the status event while loading or not.

**Comment by moreau-nicolas** [comment]
Actually groups do work, at least on my installation.
If I write ```*1*1*3##``` a whole room lights up. ```*1*0*0##``` shuts off lights everywhere.

Regarding the "load on start for lights" change you are suggesting I don't know. I'm not sure it would be useful to have lights magically turn on / off when the app loads. And it can already be done with a Device. What do you think ?

Could you please create a new issue for the # group problem? I created this issue only to discuss the additional buttons. :-)

**Comment by niqdev** [comment]
Sorry, I've misunderstood your proposal, forget the "load on start for lights".
You mean, you would like to have both toggle and on/off on the same card, right?
I will create a separate issue for group problem.

**Comment by niqdev** [comment]
I've created a separate [issue](https://github.com/openwebnet/openwebnet-android/issues/16)

**Comment by moreau-nicolas** [comment]
Yes, at the very least have on/off for lights. Once we have that we can remove the toggle, or keep it. Both are fine to me.

**Comment by niqdev** [comment]
I think we should let user configure the behaviour depending on what the WHERE command means.
In LightActivity we can add a spinner where user can choose [toggle/switch](http://developer.android.com/guide/topics/ui/controls/togglebutton.html) as default (same as now) and a second option with 2 separate action as you suggested for handle groups and scenarios.
Do you like it?

**Comment by moreau-nicolas** [comment]
I'm not sure that this should be a user preference.

It seems that this would require a lot of effort (add the spinner, modify the model, create a migration strategy, support both behaviors in the adapter, update the tests...) to provide little value: there's nothing the toggle can do that the on/off combination can't. The reverse is not true.

Is there something you don't like with having two buttons instead of one ?

**Comment by niqdev** [comment]
You are right, you convinced me! Go for it.. so no toggle and two separate buttons.

**Comment by niqdev** [comment]
I've merged the previous pull request, just let me know if you are going to remove the toggle as suggested or I will do it, so we can close the issue and release a new version, thanks

**Comment by moreau-nicolas** [comment]
Yes, I'll remove the toggle button when I get home.

**Comment by niqdev** [comment]
Well done.
I'm not sure if vector images works correctly on all devices also if we have minVersion 16.
Let me know if you are sure that it works correctly and is not needed (I had some trouble with triangles), otherwise could you please add also all the PNG under each `mipmap-XXX`.

**Comment by moreau-nicolas** [comment]
I just tried running 4ce93db on an API-16 AVD and the app fails with the same stack trace as #1.
I'm leaving for work so I'll dig a bit later, maybe on the week-end, I have a few busy days ahead.

**Comment by moreau-nicolas** [comment]
Google published a new support library for vector drawables, I think we should start using it.
See: http://android-developers.blogspot.fr/2016/02/android-support-library-232.html
Do you agree ?

Which version of Android Studio are you developing on ?

**Comment by niqdev** [comment]
If it fixes the error for sure! Currently I'm using v1.5.1

**Comment by moreau-nicolas** [comment]
Everything seems OK, now that all the PRs have been merged, I close the issue. :+1:

**Comment by niqdev** [comment]
I've merged few PRs so I don't actually know which one introduced this regression, but could you verify if you have the same problem, i.e. huge margin between cards? Thanks

![screen shot 2016-03-06 at 17 13 38](https://cloud.githubusercontent.com/assets/9458643/13555364/10996db8-e3bf-11e5-87bc-fe0b5bc14bde.png)
