### ISSUE TITLE
Handle light group

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#16]
We should support also the following light command format `*1*1 - #2 - ##`, "where" syntax with hash

**Comment by moreau-nicolas** [comment]
I think this is more a feature / enhancement than a bug, but it's just me !

**Comment by niqdev** [comment]
:wink:

**Comment by niqdev** [comment]
Updated [rx-openwebnet](https://github.com/openwebnet/rx-openwebnet) v1.3.0 to handle this feature

**Comment by niqdev** [comment]
Version 2.9.0 adds this feature
