### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#2]
Hello,

It would be nice if the project had a CONTRIBUTING.md file explaining how to contribute to the project.
I'd like to know where to send pull requests (development ? master ?).

**Comment by niqdev** [comment]
Hi,
thanks for your interest, it's a pleasure.
I'll define some guidelines and you are welcome with any suggestions.

**Comment by niqdev** [comment]
I've added [CONTRIBUTING.md](https://github.com/openwebnet/openwebnet-android/blob/development/CONTRIBUTING.md), any feedback is welcome

**Comment by moreau-nicolas** [comment]
Very nice ! :-)

**Comment by moreau-nicolas** [comment]
It seems only the repo owner can add labels. :-(

Perhaps the CONTRIBUTING.md file should just state that the name of the issue should start with the label name ?

**Comment by niqdev** [comment]
updated!
