### ISSUE TITLE
Import/Export database to JSON

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#22]
Add in Preferences the possibility to import/export all configuration for backup purposes or to share it with other devices. I would like to give the possibility to send it via email also.

**Comment by moreau-nicolas** [comment]
I'm interested ! It would help a lot with switching / testing versions !

**Comment by niqdev** [comment]
I've just checked, import should be easy `https://realm.io/docs/java/latest/#json`, while export is not supported yet, so I think we should use [GSON](https://github.com/google/gson) or open an issue to Realm ;-)

**Comment by niqdev** [comment]
I think, as first step we should allow this feature only on same database version.
As second step we should add version number also on tables and allow to import only tables with same version.
Finally we should reuse the same logic for migration strategy to determine for each table how should be imported

**Comment by niqdev** [comment]
From a review, users would like an easy way to export and share configuration, a possible solution is to integrate Google Drive.

**Comment by moreau-nicolas** [comment]
I think that Google Drive integration would be a nice feature indeed.
I'm not sure what the impacts are though.
Will this mean that we will have a dependency on Google Play Services ?

It's not necessarily a problem, I just want to make sure.
From my research Play Services seem necessary in order to implement issue #13 anyway.

**Comment by niqdev** [comment]
About Google Play Services dependency, yes if we use Drive.

I'm still thinking about that, but I wouldn't take the responsibility to store user's system configuration backup without charge them and I'd like that the app remain free.

So I think a possibility is to let users backup their data on its own otherwise another possibility is to develop a webapp and let user manage their configuration also from browser.
Would you be interested in the last option?

**Comment by moreau-nicolas** [comment]
I think there's another (simpler) way: use Android's native sharing mecanism to send the configuration data to Google Drive (or Dropbox, or OneDrive or other cloud storage providers).

Kind of when you select a picture in the Gallery and then click on "Share" : you get a menu with the list of compatible apps and can send the picture to any of them.

What do you think about this ?

**Comment by niqdev** [comment]
Yes sure, this is another option too.
Anyway, I think this feature should be the last just because less versions we have to manage and easier will be. I mean I'd like at least to add also [temperature](https://github.com/openwebnet/openwebnet-android/issues/25) and [sounds system](https://github.com/openwebnet/openwebnet-android/issues/24)

**Comment by niqdev** [comment]
Obsolete, profile feature supported in version 3+
