### ISSUE TITLE
Add support for Temperature System

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#25]
Should update also [rx-openwebnet](https://github.com/openwebnet/rx-openwebnet)

**Comment by moreau-nicolas** [comment]
I can have a look if you want.

**Comment by niqdev** [comment]
All right, just few hint

- we should handle conversion between celsius/fahrenheit? using a spinner in the activity?
- I would like to change the font, like digits only for the temperature value: see `FontViewHelper`, we should also remove unused fonts!
- we should be able to increase/decrease temperature

**Comment by niqdev** [comment]
Before that you start we need to discuss where to add to action to add it, I don't think that `FloatingActionMenu` is the right place

**Comment by moreau-nicolas** [comment]
I think that we sould create a new issue for "determine what goes in the ```FloatingActionMenu```".

Regarding the Temperature feature, [this file](http://www.myopen-legrandgroup.com/resources/own_protocol/m/own_documents/19.aspx) gives plenty of information but is not very reader-friendly.

The temperature features in MyHome seem much more complex than Lighting or Automation. I think we should proceed iteratively and maybe start with something relatively simple: only show the current temperature. Once we have that we'll move forward with more interesting things. What do you think ?

**Comment by niqdev** [comment]
For fab see this [issue](https://github.com/openwebnet/openwebnet-android/issues/39).

About temperature, agree with you about starting only from reading value.
Moreover I would like to document also each supported message/frame from `rx-openwebnet`, I already opened an [issue](https://github.com/openwebnet/rx-openwebnet/issues/5)

**Comment by niqdev** [comment]
Added temperature feature in version 2.4.x
