### ISSUE TITLE
Enhancement: gateway default port

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#32]
Hello,

At the moment the "add gateway" dialog does not tell the user that the default port is 20000.
Many users won't have too much difficulty finding the correct IP address, but the port might not be as obvious. Giving a little help can't hurt.

The fix could be as simple as modifying the existing hint ("Port") to something more explicit like "Port (default is 20000)".
Other implementations are possible:
- let the "Port" EditText be optional and use 20000 when it is empty
- add a short explanation text at the bottom of the dialog
- ...

What do you think ?

**Comment by niqdev** [comment]
Yep, nice hint. If you agree I would simply prefill the edittext with a default value.
I think initial value should be set in `GatewayEditTextPreference#onCreateDialogView` from `OpenWebNet.OpenGateway.DEFAULT_PORT`

**Comment by moreau-nicolas** [comment]
I'm not sure that pre-filling it would be "The Right Thing To Do" :tm: .
If we pre-fill the text field the user will see this:

![screenshot_20160306-175513](https://cloud.githubusercontent.com/assets/15214466/13555601/ed43cec0-e3c4-11e5-9c7d-c471130fe349.png)

We lose the information that "20000" is a port (seems pretty obvious I know but anyway).
We could have both by:
1. adding the port number in the hint text, maybe using a format string to inject the value of ```OpenWebNet.OpenGateway.DEFAULT_PORT```
2. modifying the dialog to accept an empty port, replacing it with the default value if it is empty.

I think that would give a better user experience.

**Comment by niqdev** [comment]
You are right that we loose the information that is a port, so no prefilled value.
While I don't really like that port is set automatically if empty.
User should understand what is doing, so
- or we modify the hint if we have enough space for "Port (default 20000)"
- or probably is better to add a TextView below with "Default port is 20000" in italic and/or bold

What do you think?

**Comment by moreau-nicolas** [comment]
I like the second idea: let's add a ```TextView``` below the dialog!
Could you provide me with the Italian translation of "Port (default 20000)" please ? :it:

**Comment by niqdev** [comment]
Sure!
> Porta (predefinita 20000)

**Comment by moreau-nicolas** [comment]
Thanks ! :+1:

**Comment by moreau-nicolas** [comment]
In fact i would need the translation for "Default port is 20000", it seems nicer.

**Comment by niqdev** [comment]
In theory should be
> La porta predefinita e' 20000

but I don't  like it, too long, this is better:

> Porta predefinita: 20000

**Comment by niqdev** [comment]
So also in english we should write:
> Default port: 20000
Do you agree?

**Comment by moreau-nicolas** [comment]
Would you like the English translation to be "Default port: 20000" then ?

**Comment by niqdev** [comment]
yep!
