### ISSUE TITLE
Huge margin between cards

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#33]
I've merged few PRs so I don't actually know which one introduced this regression, @moreau-nicolas could you verify if you have the same problem, i.e. huge margin between cards? Thanks

![screen shot 2016-03-06 at 17 13 38](https://cloud.githubusercontent.com/assets/9458643/13555364/10996db8-e3bf-11e5-87bc-fe0b5bc14bde.png)

**Comment by moreau-nicolas** [comment]
Yep, I'm checking it right now !

**Comment by moreau-nicolas** [comment]
This might be due to the support library version bump, see http://android-developers.blogspot.fr/2016/02/android-support-library-232.html

> # RecyclerView
> The RecyclerView widget provides an advanced and flexible base for creating lists and grids as well as supporting animations. This release brings an exciting new feature to the LayoutManager API: auto-measurement! This allows a RecyclerView to size itself based on the size of its contents.
> This means that previously unavailable scenarios, such as using WRAP_CONTENT for a dimension of the RecyclerView, are now possible. You’ll find all built in LayoutManagers now support auto-measurement.

> **Due to this change, make sure to double check the layout parameters of your item views: previously ignored layout parameters (such as MATCH_PARENT in the scroll direction) will now be fully respected.**

> If you have a custom LayoutManager that does not extend one of the built in LayoutManagers, this is an opt-in API - you’ll be required to call setAutoMeasureEnabled(true) as well as make some minor changes as detailed in the Javadoc of the method.

(emphasis mine)

This seems to be a good lead.

**Comment by niqdev** [comment]
I think so! If you are going to change the layout parameters, be sure that we still have the correct behaviour also on device orientation change.
Currently we use `GridLayoutManager` in `DeviceListFragment#onCreateView`, in particular verify `DeviceListFragment#calculateGridColumns`.
Thanks

**Comment by moreau-nicolas** [comment]
Ok, will check !

**Comment by moreau-nicolas** [comment]
Everything is fine in both portrait and landscape modes !

**Comment by niqdev** [comment]
Looks fine also to me! :thumbsup:
