### ISSUE TITLE
Bug: renaming an Environment while it is shown does not update the screen title

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#38]
## Steps to reproduce: ##
1. create an environment with the name "Example"
2. click on this environment in the drawer
3. rename the environment to "Kitchen"
4. close the drawer

The screen title still is the previous title ("Example"), not the updated one ("Kitchen").

**Comment by niqdev** [comment]
I will check this!

**Comment by niqdev** [comment]
This issue imply:

- [x] the one you described above
- [x] update the title only if the activity is the same that is already shown

when an environment is deleted and favourites are shown:

- [x] update the title (app_name)
- [x] hide fab
- [x] show loader

**Comment by niqdev** [comment]
This [8ac5bff](https://github.com/openwebnet/openwebnet-android/commit/8ac5bffbd6752b6bb128007db5f4dad1f9f0afaf) commit fix the issue
