### ISSUE TITLE
Determine what goes in the FloatingActionMenu

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#39]
As suggested, we should decide which actions go in `FloatingActionMenu` and which ones in `ActionMenu` depending on the most frequently used and that action fab menu size should not exceed 6.
Current/future actions:

- device
- light
- automation
- temperature
- sound
- ipcam
- alarm

**Comment by moreau-nicolas** [comment]
At the moment there are six items and six slots. So... Do we really have a problem ? :smiley_cat: 

Anyway, I think that "device" might be a good candidate to remove from the FAB : it is an "advanced" feature that most users shouldn't need if we support the 5 other device types.
It could be moved to a sub-menu that would appear when click on the debug bugdroid with a label that says "add custom device" or "add debug device".

Another way to do it would be to have a dedicated "sandbox" activity where users can type something and see the results. But I stray (a bit) from the main subject, sorry. 

What do you think about this ?

**Comment by niqdev** [comment]
I tried to add 7 fab, but I think even 3 probably is to much (tested on emulator api 16)

<img width="657" alt="screen shot 2016-03-09 at 18 21 10" src="https://cloud.githubusercontent.com/assets/9458643/13644008/f1c19a5c-e623-11e5-9ef5-1d59e6e9732e.png">

**Comment by moreau-nicolas** [comment]
Oh, yeah I didn't think of screen orientation. Silly me.

What do the guidelines say about FABs in landscape mode ?

**Comment by niqdev** [comment]
[Here](https://www.google.com/design/spec/components/buttons-floating-action-button.html) there is no explanation, but have a look at trello app, they hide action if there is no more space.
Also the alpha background would be great!

![screenshot_2016-03-09-19-09-53](https://cloud.githubusercontent.com/assets/9458643/13645374/050d88b2-e62b-11e5-96c9-0a3e82ffe82c.png)
![screenshot_2016-03-09-19-10-01](https://cloud.githubusercontent.com/assets/9458643/13645376/052d2226-e62b-11e5-9a93-c1d1b10ed40e.png)

**Comment by moreau-nicolas** [comment]
Reading through the guidelines I found [this video](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-TjBicTdvQjg4M1E/components-buttons-fab-transition_card_02.webm).
What do you think about it ?

It would obviously solve the landscape orientation issue as the new material sheet can be scrollable, that's common UI practice.

[This other video](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-RWVHZjYybnlDeUE/components-buttons-fab-transition_fullscreen_02.webm) that I thought could help shows that the button can transform into a fullscreen experience. That gave me an idea : we could leverage the fact that support libraries version 23.2 provide the **[bottom sheet](https://www.google.com/design/spec/components/bottom-sheets.html)** functionality to make a bottom sheet appear on FAB click. It's not-that-different from the "new material sheet" idea above, just a slight variation.

Regarding how Trello does things, I have played a bit with the app on my phone and in fact they **don't** handle the landscape situation at all : I can see the tip of a button just under the Action bar. It might depend on a screen size though. That would explain why your screenshot looks fine.

**Comment by niqdev** [comment]
Reading the docs, it seems that we need a modal bottom sheet, than we can choose between List-style and Grid-style. As you said this is scrollable.
So the idea is to open a modal bottom sheet from a fab? Than user can select and action and open the corresponding activity or dismiss the modal scrolling it down/touching above the modal (in the grey area)?
I've added Alarm action to the list as nice to have and opened an [issue](https://github.com/openwebnet/openwebnet-android/issues/41)

**Comment by moreau-nicolas** [comment]
Yes, I agree with removing the menu and adding a bottom sheet. It won't be as pretty as the menu, but it will be more scalable.

**Comment by moreau-nicolas** [comment]
Yes, I agree with removing the menu and adding a bottom sheet. It won't be as pretty as the menu, but it will be more scalable.

**Comment by niqdev** [comment]
I will work on this.
Just to be sure, @moreau-nicolas I will substitute FAB with native implementation and use it to show the `BottomSheet`, do you agree?

**Comment by moreau-nicolas** [comment]
Sorry for the late answer. What do you mean by "native implementation" ?

**Comment by niqdev** [comment]
Don't worry, I'm already working on this on a new branch, actually there are 3 solutions:

- example of [native](https://github.com/vipulshah2010/BottomSheets) solution: I have to manage the icon menu grid on my own
- I like [Flipboard](https://github.com/Flipboard/bottomsheet) style but there is a problem, the dark layer doesn't cover the AppBar/Toolbar
- other [library](https://github.com/soarcn/BottomSheet), but as the author says, is no more supported

**Comment by moreau-nicolas** [comment]
Please use the Google support library ! Version 23.0.2 (which we already use for vector-drawable support) provides a "bottom sheets" implementation . :)

**Comment by niqdev** [comment]
All support libraries have been updated to the latest version i.e. `23.2.1`, there was a bug with fab.
Now both FAB and BottomSheet are natives.

I've almost finished, but I need help for icons, I would like to have nice vector drawable icons, not png. Could you help me @moreau-nicolas to update the icons, please?
Now I've used [this](http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) to generate them.
I'm currently working on this branch: `fab-bottom-sheet`

![screen shot 2016-03-19 at 18 36 35](https://cloud.githubusercontent.com/assets/9458643/13900239/ebe07e56-ee01-11e5-8fbc-0a79aa40b7bd.png)

**Comment by niqdev** [comment]
Implementation and tests are completed, I must only change the menu icons

**Comment by niqdev** [comment]
Final result, only long shadow is missing!

![screenshot-bs-01](https://cloud.githubusercontent.com/assets/9458643/13903498/2cbd14b2-ee7e-11e5-821e-14c2299c3fff.png)

**Comment by niqdev** [comment]
Version `2.0.0` should be available in few hours only for beta tester.
@moreau-nicolas, if you wish to improve something let me know, otherwise I will release the app in prod next days.
Thanks

**Comment by moreau-nicolas** [comment]
Congrats, the final result looks very nice ! :)

The only thing I'd like to change from the screenshot above would be to use a circle-shaped background for the icons rather than a square-shaped one: using the same shape connects the actions with the FAB because they are both circles. But squares are fine too, it's just a matter of taste.

**Comment by niqdev** [comment]
Honestly I don't really know, [docs](https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-specs) don't say anything about that, but [fab docs](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) lists a lot of "don't do it" and it seems that they suggest to use only circle for actions, but I really don't know.
We can try maybe and see how it looks.

**Comment by moreau-nicolas** [comment]
Yes, it was just a suggestion. :)
