### ISSUE TITLE
Add German translations

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#56]
Translate the app in German

**Comment by niqdev** [comment]
[Hacktoberfest] Please contact me to have more info about this issue, any help would be very appreciated. Thanks

**Comment by parideis** [comment]
Hi, do you have a single file to translate, or do we have to make changes across the app?

**Comment by niqdev** [comment]
Hi @parideis , thanks for your interest, there is a single [strings.xml](https://github.com/openwebnet/openwebnet-android/blob/master/app/src/main/res/values/strings.xml) to be translated, and not even all the keys. You could copy the [italian](https://github.com/openwebnet/openwebnet-android/blob/master/app/src/main/res/values-it/strings.xml) translation and translate only that keywords.
Let me know if you need any help, please refer to the [CONTRIBUTING](https://github.com/openwebnet/openwebnet-android/blob/master/CONTRIBUTING.md) guideline.
Thanks

**Comment by niqdev** [comment]
@parideis Thanks! I'll release a new version of the app in the store and I'll add you to the list of contributors!

**Comment by niqdev** [comment]
@parideis Sorry, I completely forgot of the store listing for the Play Store, would you mind to translate also [st_en.md](https://github.com/openwebnet/openwebnet-android/blob/master/store-listing/st_en.md)?
Thanks a lot

**Comment by parideis** [comment]
@niqdev no worries, I will also translate that for you :)

**Comment by schwedenmut** [comment]
@niqdev and @parideis i went ahead and translated the Google Play entry to German.

**Comment by niqdev** [comment]
thanks a lot to both!
