### ISSUE TITLE
Enhancement: card buttons should give a visual feedback

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#8]
Hello,

At the moment it's quite hard to see if a button click on a card registers or not. Having visual feedback would help a lot.
A solution would be to use ```StateListDrawable```s instead of plain-ol' XML drawables for ```ImageButton```s.

This will require some graphics skill to create the hover / pressed / whatever icon variants (a simple color change might not be enough).

**Comment by niqdev** [comment]
Hi,
this would be nice!

**Comment by moreau-nicolas** [comment]
Have you got any experience with SVG / graphics editing ?

**Comment by niqdev** [comment]
Unfortunately no, I've no experience at all on graphics. That's why I've used [materialdesignicons](https://materialdesignicons.com/) ;-)

**Comment by moreau-nicolas** [comment]
Ok, perhaps the state list drawable I was suggesting is not the best solution :

1. It is not very Material-like
2. It requires graphics-related work that we're both not very comfortable with.

Reading the Material Design Guidelines' section about UI feedback I'm thinking that adding a "ripple effect" to the buttons would be a better solution. What do you think ?

If you're Ok with it I'd like to implement it.

**Comment by niqdev** [comment]
Sounds good!

**Comment by niqdev** [comment]
So, just to understand, the change was: use `ImageButton` and add `android:background="?attr/selectableItemBackgroundBorderless"`, right?

**Comment by moreau-nicolas** [comment]
Yes, even though using ```ImageButton``` wasn't strictly necessary, I just thought it better expressed the intent that the image is to be used as a button. The background attribute does all the work.

**Comment by niqdev** [comment]
Great!
