### ISSUE TITLE
Support for BTI-3583 gateway

### ISSUE THREAD

**Issue by bogdanripa** [openwebnet/openwebnet-android#80]
Please add support for the BTI-3583 gateway:

![image](https://user-images.githubusercontent.com/1695752/37215521-d0c18bd2-23c0-11e8-9031-f2bb96df8c64.png)

For some reason, the OpenWebNet implementation on the above gateway does not work as expected. See bellow:

```
echo "*#13**15##" | nc 192.168.86.95 20000
*#*1##*#*0##
```

**Comment by niqdev** [comment]
Hi,
could you please provide more informations about your problem?
What's the meaning of the frame in your example and what should be the expected result?
Did you try to enable the debug feature from the app and send custom frame to your gateway? Do you have the same result?
The android client should work with any gateway. Keep in mind that if you need to provide credentials to access the gateway you probably need to send additional frames.
Let me know if you need more help,
Thanks

**Comment by niqdev** [comment]
Obsolete
