### ISSUE TITLE
Enhancement: provide a means to delete an Environment

### ISSUE THREAD

**Issue by moreau-nicolas** [openwebnet/openwebnet-android#9]
Hello,

At the moment one can create many Environments but the only means I found to delete one is to "delete all data" in the system settings for the app. There should be an user-friendlier way to do this !

Perhaps creating a dedicated ```EnvironmentActivity``` to manage environments would help with this ?
The activity could let users Add / Edit / Remove any environment (and associated lights / devices).

**Comment by niqdev** [comment]
Hi,
currently in `NavigationViewClickListener#showDialogEditEnvironment` there is already a delete Environment, but is not implemented. Is the 3rd button in the dialog.
Implemented in this way, pressing delete will remove an environment and delete all associated devices/lights without asking for a confirmation.
Another solution, but it requires more refactoring, is to add an entry (item menu) in NavigationDrawer under "Add environment" to toggle (show/hide) edit and delete icons next to each environment entry.
First solution is easy and faster.

**Comment by moreau-nicolas** [comment]
Actually I really like the idea of having a separate screen for the environment.

If you think in terms of SOLID design principles, the navigation drawer should have a single responsibility: navigation !

I agree that a delete button will be faster to implement and maybe we can start with that.
What do you think about this ?

**Comment by moreau-nicolas** [comment]
Yes! How do we proceed ? Do I do it ? Do you ?

**Comment by niqdev** [comment]
I'm going to start a new project soon and I need time to study Scala/Play, so for few months I will slow down my development on this app, later I will continue to add my planned features.
Feel free to open new issues, I will be happy to discuss them with you and merge your pull requests!

**Comment by niqdev** [comment]
I'm working also on other stuff/projects, so maybe I will do it later, otherwise the first that start working on will write it here and I will assign this issue

**Comment by niqdev** [comment]
Just for reference, please look at this [comment](https://github.com/openwebnet/openwebnet-android/pull/29/files) on file `EnvironmentRepositoryImpl`

**Comment by niqdev** [comment]
I've checked again and before merging the PR I need you to verify what happen if user delete all environments.
Currently there is a check in `EnvironmentRepositoryImpl#getNextId` that should expects at least 1 environment.
You can verify also field `orderInCategory` in `menu/activity_main_drawer.xml`, all environment menu item order should be greater than 100.

**Comment by moreau-nicolas** [comment]
Everything seemed fine yesterday: when we remove every environment the navigation menu only shows the "add environment" entry, which seems appropriate. I didn't see any errors.

But I didn't try killing the app and starting it again, in case something stays in memory. I'll test it tonight.

**Comment by moreau-nicolas** [comment]
I can confirm that deleting all environments, killing the app and restarting it does not produce any error.

Here is what it looks like:
![screenshot_20160308-223412](https://cloud.githubusercontent.com/assets/15214466/13618854/8e826108-e586-11e5-8ca5-aa91eb48d520.png)

I think it is safe to merge PR #29 and close this issue.

**Comment by niqdev** [comment]
Well done!

**Comment by niqdev** [comment]
Could you please translate this in french?
>
Fix error on android 4.1
Delete environments
Minor style changes

**Comment by niqdev** [comment]
Version 1.4.2 is in beta now, should be available for download in few hours

**Comment by moreau-nicolas** [comment]
Here goes the translation:

> Correction d'erreur sur les appareils sous Android 4.1
> Ajout de la possibilité de supprimer un environnement
> Changements mineurs d'apparence

It's not a one-to-one translation, but it expresses what has changed. I guess it's for the Changelog ?

**Comment by niqdev** [comment]
Yep, thanks!
